using System.CommandLine;
using RepoIdentity.Services;

namespace RepoIdentity.Commands;

internal static class GenerateCommand
{
    private const string ScriptTemplate =
        """
        # Set-RepoTheme.ps1
        # Auto-generated by repo-identity. Do not edit manually — re-run 'repo-identity generate' to update.
        # Safe to call on every directory change — switches theme per repo, resets to default elsewhere.

        $ErrorActionPreference = 'SilentlyContinue'

        $poshThemesDir = Join-Path $HOME '.poshthemes'

        # Resolve the tracked repo for the current directory (empty string = not tracked)
        $fullName = ''
        $repoRoot = git rev-parse --show-toplevel 2>$null
        if ($repoRoot) {
            $remote = git -C $repoRoot remote get-url origin 2>$null
            if ($remote -and $remote -match 'github\.com[:/](.+?)(?:\.git)?$') {
                $fullName = $matches[1]
            }
        }

        # Look up whether this repo has a theme
        $entry = $null
        if ($fullName) {
            $indexPath = Join-Path $poshThemesDir 'index.json'
            if (Test-Path $indexPath) {
                $index = Get-Content $indexPath -Raw | ConvertFrom-Json
                $entry = $index.profiles | Where-Object { $_.repo -eq $fullName } | Select-Object -First 1
            }
        }

        if ($entry) {
            # Tracked repo — apply its theme (skip if already active)
            if ($global:_repoIdentityLast -eq $fullName) { return }
            $configFile = Join-Path $poshThemesDir $entry.configFile
            if (-not (Test-Path $configFile)) { return }
            $global:_repoIdentityLast = $fullName
            oh-my-posh init pwsh --config $configFile | Invoke-Expression
        } else {
            # Not a tracked repo — reset to default if we were showing a custom theme
            if ($global:_repoIdentityLast -eq '') { return }
            $global:_repoIdentityLast = ''
            $defaultConfig = Join-Path $poshThemesDir 'default.json'
            if (Test-Path $defaultConfig) {
                oh-my-posh init pwsh --config $defaultConfig | Invoke-Expression
            } else {
                oh-my-posh init pwsh | Invoke-Expression
            }
        }
        """;

    private const string DefaultThemeJson = """
        {
          "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
          "version": 2,
          "console_title_template": "{{ .Shell }} · {{ .PWD }}",
          "blocks": [
            {
              "type": "prompt",
              "alignment": "left",
              "segments": [
                {
                  "type": "path",
                  "foreground": "#9CDCFE",
                  "background": "#2D2D2D",
                  "style": "plain",
                  "template": " {{ .Path }} "
                },
                {
                  "type": "git",
                  "foreground": "#6A9955",
                  "background": "#2D2D2D",
                  "style": "plain",
                  "template": " {{ .HEAD }}{{ if .Working.Changed }}*{{ end }} "
                },
                {
                  "type": "text",
                  "foreground": "#D4D4D4",
                  "background": "transparent",
                  "style": "plain",
                  "template": "❯ "
                }
              ]
            }
          ]
        }
        """;

    internal static Command Create()
    {
        var sourceOption = new Option<FileInfo>(
            "--source",
            () => new FileInfo(Path.Combine(Directory.GetCurrentDirectory(), "data", "latest", "data.repositories.json")),
            "Path to data.repositories.json produced by the dashboard pipeline");

        var outputOption = new Option<DirectoryInfo>(
            "--output",
            () => new DirectoryInfo(Path.Combine(Directory.GetCurrentDirectory(), "terminal", "ohmyposh")),
            "Directory to write generated Oh My Posh config files");

        var command = new Command("generate", "Generate Oh My Posh config files from tracked repos")
        {
            sourceOption,
            outputOption
        };

        command.SetHandler(async (FileInfo source, DirectoryInfo output) =>
        {
            var reader = new DashboardDataReader();
            var colorGen = new ColorGenerator();
            var configGen = new ConfigGenerator(colorGen);

            Console.WriteLine($"Reading repos from: {source.FullName}");
            var data = await reader.ReadAsync(source.FullName);

            Console.WriteLine($"Found {data.Repositories.Count} repos. Generating profiles...");
            var result = await configGen.GenerateAsync(data.Repositories, output.FullName);

            Console.WriteLine($"✅ Generated {result.FilesGenerated} profile(s) → {result.OutputDirectory}");
            foreach (var file in result.GeneratedFiles.Where(f => !f.EndsWith("index.json")))
                Console.WriteLine($"   {Path.GetFileName(file)}");
            Console.WriteLine($"   index.json");

            // Also write the auto-detection script
            var scriptPath = Path.Combine(output.FullName, "Set-RepoTheme.ps1");
            await File.WriteAllTextAsync(scriptPath, ScriptTemplate.Replace("\r\n", "\n"));
            Console.WriteLine($"   Set-RepoTheme.ps1");

            // Write default.json if not already present (user may have customised it)
            var defaultPath = Path.Combine(output.FullName, "default.json");
            if (!File.Exists(defaultPath))
            {
                await File.WriteAllTextAsync(defaultPath, DefaultThemeJson.Replace("\r\n", "\n"));
                Console.WriteLine($"   default.json (neutral fallback theme)");
            }
        }, sourceOption, outputOption);

        return command;
    }
}
