using System.CommandLine;
using RepoIdentity.Services;

namespace RepoIdentity.Commands;

internal static class GenerateCommand
{
    private const string ScriptTemplate =
        """
        # Set-RepoTheme.ps1
        # Auto-generated by repo-identity. Do not edit manually — re-run 'repo-identity generate' to update.
        # Called from $PROFILE on every shell start to apply the theme for the current git repository.

        $ErrorActionPreference = 'SilentlyContinue'

        # Step 1: Find the current git repo root
        $repoRoot = git rev-parse --show-toplevel 2>$null
        if (-not $repoRoot) { return }

        # Step 2: Get the remote URL and extract owner/repo
        $remote = git -C $repoRoot remote get-url origin 2>$null
        if (-not $remote) { return }

        $fullName = $null
        if ($remote -match 'github\.com[:/](.+?)(?:\.git)?$') {
            $fullName = $matches[1]
        }
        if (-not $fullName) { return }

        # Step 3: Locate index.json in ~/.poshthemes
        $poshThemesDir = Join-Path $HOME '.poshthemes'
        $indexPath = Join-Path $poshThemesDir 'index.json'
        if (-not (Test-Path $indexPath)) { return }

        # Step 4: Look up the profile for this repo
        $index = Get-Content $indexPath -Raw | ConvertFrom-Json
        $entry = $index.profiles | Where-Object { $_.repo -eq $fullName } | Select-Object -First 1
        if (-not $entry) { return }

        # Step 5: Apply the Oh My Posh theme
        $configFile = Join-Path $poshThemesDir $entry.configFile
        if (-not (Test-Path $configFile)) { return }

        oh-my-posh init pwsh --config $configFile | Invoke-Expression
        """;

    internal static Command Create()
    {
        var sourceOption = new Option<FileInfo>(
            "--source",
            () => new FileInfo(Path.Combine(Directory.GetCurrentDirectory(), "data", "latest", "data.repositories.json")),
            "Path to data.repositories.json produced by the dashboard pipeline");

        var outputOption = new Option<DirectoryInfo>(
            "--output",
            () => new DirectoryInfo(Path.Combine(Directory.GetCurrentDirectory(), "terminal", "ohmyposh")),
            "Directory to write generated Oh My Posh config files");

        var command = new Command("generate", "Generate Oh My Posh config files from tracked repos")
        {
            sourceOption,
            outputOption
        };

        command.SetHandler(async (FileInfo source, DirectoryInfo output) =>
        {
            var reader = new DashboardDataReader();
            var colorGen = new ColorGenerator();
            var configGen = new ConfigGenerator(colorGen);

            Console.WriteLine($"Reading repos from: {source.FullName}");
            var data = await reader.ReadAsync(source.FullName);

            Console.WriteLine($"Found {data.Repositories.Count} repos. Generating profiles...");
            var result = await configGen.GenerateAsync(data.Repositories, output.FullName);

            Console.WriteLine($"✅ Generated {result.FilesGenerated} profile(s) → {result.OutputDirectory}");
            foreach (var file in result.GeneratedFiles.Where(f => !f.EndsWith("index.json")))
                Console.WriteLine($"   {Path.GetFileName(file)}");
            Console.WriteLine($"   index.json");

            // Also write the auto-detection script
            var scriptPath = Path.Combine(output.FullName, "Set-RepoTheme.ps1");
            await File.WriteAllTextAsync(scriptPath, ScriptTemplate.Replace("\r\n", "\n"));
            Console.WriteLine($"   Set-RepoTheme.ps1");
        }, sourceOption, outputOption);

        return command;
    }
}
