# Set-RepoTheme.ps1
# Auto-generated by repo-identity. Do not edit manually — re-run 'repo-identity generate' to update.
# Safe to call on every directory change — switches theme per repo, resets to default elsewhere.

$ErrorActionPreference = 'SilentlyContinue'

$poshThemesDir = Join-Path $HOME '.poshthemes'

# Resolve the tracked repo for the current directory (empty string = not tracked)
$fullName = ''
$repoRoot = git rev-parse --show-toplevel 2>$null
if ($repoRoot) {
    $remote = git -C $repoRoot remote get-url origin 2>$null
    if ($remote -and $remote -match 'github\.com[:/](.+?)(?:\.git)?$') {
        $fullName = $matches[1]
    }
}

# Look up whether this repo has a theme
$entry = $null
if ($fullName) {
    $indexPath = Join-Path $poshThemesDir 'index.json'
    if (Test-Path $indexPath) {
        $index = Get-Content $indexPath -Raw | ConvertFrom-Json
        $entry = $index.profiles | Where-Object { $_.repo -eq $fullName } | Select-Object -First 1
    }
}

if ($entry) {
    # Tracked repo — apply its theme (skip if already active)
    if ($global:_repoIdentityLast -eq $fullName) { return }
    $configFile = Join-Path $poshThemesDir $entry.configFile
    if (-not (Test-Path $configFile)) { return }
    $global:_repoIdentityLast = $fullName
    oh-my-posh init pwsh --config $configFile | Invoke-Expression
} else {
    # Not a tracked repo — reset to default if we were showing a custom theme
    if ($global:_repoIdentityLast -eq '') { return }
    $global:_repoIdentityLast = ''
    $defaultConfig = Join-Path $poshThemesDir 'default.json'
    if (Test-Path $defaultConfig) {
        oh-my-posh init pwsh --config $defaultConfig | Invoke-Expression
    } else {
        oh-my-posh init pwsh | Invoke-Expression
    }
}