# Set-RepoTheme.ps1
# Auto-generated by repo-identity. Do not edit manually — re-run 'repo-identity generate' to update.
# Safe to call on every directory change — skips re-init when the repo hasn't changed.

$ErrorActionPreference = 'SilentlyContinue'

# Step 1: Find the current git repo root
$repoRoot = git rev-parse --show-toplevel 2>$null
if (-not $repoRoot) { return }

# Step 2: Get the remote URL and extract owner/repo
$remote = git -C $repoRoot remote get-url origin 2>$null
if (-not $remote) { return }

$fullName = $null
if ($remote -match 'github\.com[:/](.+?)(?:\.git)?$') {
    $fullName = $matches[1]
}
if (-not $fullName) { return }

# Skip re-initialization if we're already showing this repo's theme
if ($global:_repoIdentityLast -eq $fullName) { return }

# Step 3: Locate index.json in ~/.poshthemes
$poshThemesDir = Join-Path $HOME '.poshthemes'
$indexPath = Join-Path $poshThemesDir 'index.json'
if (-not (Test-Path $indexPath)) { return }

# Step 4: Look up the profile for this repo
$index = Get-Content $indexPath -Raw | ConvertFrom-Json
$entry = $index.profiles | Where-Object { $_.repo -eq $fullName } | Select-Object -First 1
if (-not $entry) { return }

# Step 5: Apply the Oh My Posh theme
$configFile = Join-Path $poshThemesDir $entry.configFile
if (-not (Test-Path $configFile)) { return }

$global:_repoIdentityLast = $fullName
oh-my-posh init pwsh --config $configFile | Invoke-Expression